# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

# Ensure role dependencies are in place
if [ "up", "provision" ].include?(ARGV.first) && File.directory?("roles") &&
  !(File.directory?("roles/azavea.logstash") || File.symlink?("roles/azavea.logstash")) ||
  !(File.directory?("roles/azavea.java") || File.symlink?("roles/azavea.java")) ||
  !(File.directory?("roles/azavea.elasticsearch") || File.symlink?("roles/azavea.elasticsearch")) ||
  !(File.directory?("roles/azavea.unzip") || File.symlink?("roles/azavea.unzip"))
  system("ansible-galaxy install --force -r roles.txt -p roles")
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 5601, host: 5601

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
    ansible.sudo = true
  end
end
